services:
  mysql:
    image: mysql:8.0
    container_name: todolist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptest123"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=todolist;user=root;password=test123;
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql-data:
